### ISSUE TITLE
Glow map - Ami sounds weird

### ISSUE THREAD

**Issue by fireattack** [KinoMyu/Million-Live-Quintet-Player#1]
I understand this is likely not an issue with the project per se but the resource, but this track sounds very weird (like a lot of echo?).

Just wondering if you know why.

Thanks!

**Comment by KinoMyu** [comment]
The game uses 012mam for both Ami's and Mami's vocal tracks when they are singing solo. However, when both of them are singing together, the game will use both 011maw (w for double) and 012mam to avoid having one loud vocal track. For simplicity's sake, I did not include logic to do this (as someone might put Ami/Mami in more than 2 slots).

**Comment by fireattack** [comment]
Thanks, that explains it!
