### ISSUE TITLE
Ami isn't playable in EVERYDAY STARS!! (and something about White Vows, too)

### ISSUE THREAD

**Issue by CW-Ballard** [KinoMyu/Million-Live-Quintet-Player#2]
So, I noticed something about Ami's voice track in "EVERYDAY STARS!!." It's named "011ami," so whenever I play it, member three (two) reverts to member one (zero). The file should be named "011maw" so she can be playable. Also, you should add Shika and Leon to "White Vows," for their appeals. I hope you get this.

**Comment by fireattack** [comment]
See #1

**Comment by KinoMyu** [comment]
Uploaded new release with the fixes. Thanks!
